### ISSUE TITLE
Paste button non-functional

### ISSUE THREAD

**Issue by isanignog** [asiekierka/TIC-80#2]
Pasting into the code editor after copying/cutting doesn't do anything. I am unsure if this is due to the clipboard remaining empty after copying/cutting, or the paste button itself not functioning. Installed from .cia, running on New 3DS XL, system version 11.14.0-46U, Luma version 10.2.1-c058e3f.

**Comment by asiekierka** [comment]
The 3DS version has been upstreamed. Please use the mainline version.
